### ISSUE TITLE
feature: add more technical indicators

### ISSUE THREAD

**Issue by narumiruna** [c9s/bbgo#217]
[7 Technical Indicators to Build a Trading Toolkit](https://www.investopedia.com/top-7-technical-analysis-tools-4773275)
[TA-Lib](https://github.com/mrjbq7/ta-lib#supported-indicators-and-functions)
[Technical Analysis Library in Python](https://github.com/bukosabino/ta)

- [x] On-Balance Volume (OBV) #226 
- [x] Accumulation/Distribution Indicator (A/D) #227 
- [ ] Average Directional Index (ADX)
- [ ] Aroon Oscillator
- [x] Moving Average Convergence Divergence (MACD) #219
- [x] Relative Strength Index (RSI) #500
- [x] Stochastic Oscillator (KD) #250
- [x] Average True Range (ATR) #536
